//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGEVN.Services.Implement
{
    using System;
    using System.Collections.Generic;

    public sealed class WS_RESP_PARS
    {
        public string RESP_RESULT { get; set; }
        public string RESP_TIME { get; set; }
        public string RESP_MSG { get; set; }
        public string CUST_SEND_ID { get; set; }
        public string SHOP_CODE { get; set; }
    }
}
