//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGEVN.Services.Implement
{
    using System;
    using System.Collections.Generic;

    public sealed class TB_CM_SHOP_BILLTO
    {
        public string BILLTO_CODE { get; set; }
        public string SHOP_CODE { get; set; }
        public DateTime? CREATE_DATE { get; set; }
        public DateTime? MODIFY_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public string MODIFY_USER { get; set; }
        public string USE_FLAG { get; set; }
        public string SO_TRANSFER_FLAG { get; set; }
        public DateTime? SO_TRANSFER_DATE { get; set; }
    }
}
