//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGEVN.Services.Implement
{
    using System;
    using System.Collections.Generic;

    public sealed class TB_CM_BILLTO_INF
    {
        public string BILLTO_CODE { get; set; }
        public string PROFILE { get; set; }
        public string SHORT_NAME { get; set; }
        public string FULL_NAME { get; set; }
        public string REPRESENTATIVE { get; set; }
        public string BIZ_NO { get; set; }
        public string TAX_ID { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string ADDRESS { get; set; }
        public string CREDIT_LEVEL { get; set; }
        public string GRADE { get; set; }
        public string HIGH_SALE_CHANNEL { get; set; }
        public string PAY_FROM { get; set; }
        public string LOW_PRICE_GROUP { get; set; }
        public string HIGH_PRICE_GROUP { get; set; }
        public string VN_DEPARTMENT { get; set; }
        public string AVTIVE { get; set; }
        public string LOW_SALE_CHANNEL { get; set; }
        public string BUYING_GROUP { get; set; }
        public string SO_TRANSFER_FLAG { get; set; }
        public DateTime? SO_TRANSFER_DATE { get; set; }
    }
}
