//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGEVN.Services.Implement
{
    using System;
    using System.Collections.Generic;

    public sealed class TB_SN_SO_DEALERS
    {
        public string SHOP_CODE { get; set; }
        public string SERIAL_NO { get; set; }
        public string BOX_NO { get; set; }
        public string MODEL { get; set; }
        public string MODEL_DESC { get; set; }
        public string EDI_NO { get; set; }
        public System.DateTime SELLOUT_DATE { get; set; }
        public string EU_CELL { get; set; }
        public string EU_NAME { get; set; }
        public string EU_ADDRESS { get; set; }
        public DateTime? UPDATE_DATE { get; set; }
        public string UPLOAD_USER { get; set; }
        public string VRF_FLAG { get; set; }
        public string SUFFIX { get; set; }
        public string CFM_FLAG { get; set; }
        public string CFM_USER { get; set; }
        public DateTime? CFM_DATE { get; set; }
        public string CFM_COMMENT { get; set; }
        public DateTime? SELLIN_DATE { get; set; }
        public string EDI_DATE { get; set; }
        public string EDI_FILE { get; set; }
        public string SO_TRANSFER_FLAG { get; set; }
        public DateTime? SO_TRANSFER_DATE { get; set; }
    }
}
