//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGEVN.Services.Implement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SN_CDC_HIST
    {
        public string INV_ORG { get; set; }
        public string LOADPLAN_NO { get; set; }
        public string SERIAL_NO { get; set; }
        public string BOX_NO { get; set; }
        public string SHIPTO_CODE { get; set; }
        public string SHIPTO_NAME { get; set; }
        public DateTime? SHIPTO_DATE { get; set; }
        public string ORDER_NO { get; set; }
        public DateTime? CLOSED_DATE { get; set; }
        public string INVOICE_NO { get; set; }
        public DateTime? INVOICE_DATE { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public System.DateTime UNIQUE_ID { get; set; }
        public string SELLOUT_FLAG { get; set; }
        public DateTime? SELLOUT_DATE { get; set; }
        public string INCENTIVE_FLAG { get; set; }
        public string WARRANTY_IF_FLAG { get; set; }
        public DateTime? WARRANTY_IF_DATE { get; set; }
        public string SEQ_NO { get; set; }
        public string MODEL_SUFFIX { get; set; }
        public string MODEL { get; set; }
        public string SUFFIX { get; set; }
    }
}
