//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGEVN.Services.Implement
{
    using System;
    using System.Collections.Generic;

    public sealed class TB_SN_PND_HIST
    {
        public string SERIAL_NO { get; set; }
        public string MOSEQ { get; set; }
        public string RESP_TYPE { get; set; }
        public string CMDCODE { get; set; }
        public DateTime? RECEIVE_DATE { get; set; }
        public Nullable<short> PND_DAYS { get; set; }
        public string CFM_FLAG { get; set; }
        public string CFM_TYPE { get; set; }
        public DateTime? CFM_DATE { get; set; }
        public string SHOP_CELL { get; set; }
        public string RESP_MSG { get; set; }
        public string MODEL { get; set; }
        public string CFM_USER { get; set; }
        public string MO_MSGBODY { get; set; }
        public string END_USER_CELL { get; set; }
        public string PND_TYPE { get; set; }
        public string SHOP_CODE { get; set; }
        public string SMS_YN { get; set; }
        public string REJECT_FLAG { get; set; }
        public DateTime? REJECT_DATE { get; set; }
        public string REJECT_USER { get; set; }
        public string SO_TRANSFER_FLAG { get; set; }
        public DateTime? SO_TRANSFER_DATE { get; set; }
    }
}
