//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGEVN.Services.Implement
{
    using System;
    using System.Collections.Generic;

    public sealed class TB_CM_SHIPTO_INF
    {
        public string BILLTO_CODE { get; set; }
        public string BILLTO_NAME { get; set; }
        public string BILLTO_FULLNAME { get; set; }
        public string BILLTO_ADDRESS1 { get; set; }
        public string SHIPTO_CODE { get; set; }
        public string SHIPTO_NAME { get; set; }
        public string SHIPTO_FULLNAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string ADDRESS4 { get; set; }
        public string POSTAL_CODE { get; set; }
        public string COUNTRY { get; set; }
        public string CITY { get; set; }
        public string BIZ_REG { get; set; }
        public string SHIPTO_STATUS { get; set; }
        public string MARKET_TYPE { get; set; }
        public string SALES_CHANNEL { get; set; }
        public string ACTIVE_FLAG { get; set; }
    }
}
