//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGEVN.Services.Implement
{
    using System;
    using System.Collections.Generic;

    public sealed class TB_CM_SHOP_INF
    {
        public string BILLTO_CODE { get; set; }
        public string SHOP_CODE { get; set; }
        public string SHOP_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string CELL_NO_1 { get; set; }
        public string DIST_CODE { get; set; }
        public string PROVINCE_CODE { get; set; }
        public DateTime? CREATE_DATE { get; set; }
        public DateTime? UPDATE_DATE { get; set; }
        public string ISDN_NO { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string AREA_CODE { get; set; }
        public string CELL_NO_2 { get; set; }
        public string OWNER_NAME { get; set; }
        public string OWNER_EMAIL { get; set; }
        public string USE_FLAG { get; set; }
        public string CHANNEL { get; set; }
        public string REG_ID { get; set; }
        public string CREATE_USER { get; set; }
        public string UPDATE_USER { get; set; }
        public string SHOP_TYPE { get; set; }
    }
}
