//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGEVN.Services.Implement
{
    using System;
    using System.Collections.Generic;

    public sealed class TB_CM_PROVINCE
    {
        public decimal ID { get; set; }
        public string REGION_ID { get; set; }
        public string NAME { get; set; }
        public decimal? LNG { get; set; }
        public decimal? LAT { get; set; }
        public decimal? ENTRY_USER_ID { get; set; }
        public string ENTRY_USER_NAME { get; set; }
        public DateTime? ENTRY_DATE_TIME { get; set; }
        public decimal? UPDATE_USER_ID { get; set; }
        public string UPDATE_USER_NAME { get; set; }
        public DateTime? UPDATE_DATE_TIME { get; set; }
        public string SO_TRANSFER_FLAG { get; set; }
        public DateTime? SO_TRANSFER_DATE { get; set; }
    }
}
