//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGEVN.Services.Implement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CM_MODEL_CAT
    {
        public string PROD_L1 { get; set; }
        public string MODEL { get; set; }
        public DateTime? CREATE_DATE { get; set; }
        public string SUFFIX { get; set; }
        public string MP_MODEL { get; set; }
        public string MP_SUFFIX { get; set; }
        public string ACTIVE_CODE { get; set; }
        public string SALE_FLAG { get; set; }
        public string PROD_L2 { get; set; }
        public string PROD_L3 { get; set; }
        public string PROD_L4 { get; set; }
        public string TENTATIVE_FLAG { get; set; }
        public string MODEL_SPEC { get; set; }
        public string PUR_TYPE { get; set; }
        public string ENABLE_FLAG { get; set; }
        public DateTime? LAST_UPDATE_DATE { get; set; }
        public string UNIT { get; set; }
        public string AU_CODE { get; set; }
        public string AF_CODE { get; set; }
        public string EOM { get; set; }
        public string PROD_TYPE { get; set; }
        public string MKT { get; set; }
        public DateTime? IF_DATE { get; set; }
    }
}
