//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGEVN.Services.Implement
{
    using System;
    using System.Collections.Generic;

    public sealed class TB_MT_SMS_RESP_MSG
    {
        public string RESP_TYPE { get; set; }
        public string RESP_MSG_1 { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string MSGBODY_LEN { get; set; }
        public string RESP_MSG_2 { get; set; }
        public string GABIT_TEMPLATE { get; set; }
        public string GABIT_ID { get; set; }
        public string TEMPLATE { get; set; }
        public string PURPOSE { get; set; }
        public string SO_TRANSFER_FLAG { get; set; }
        public DateTime? SO_TRANSFER_DATE { get; set; }
    }
}
