//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGEVN.Services.Implement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MT_HIST
    {
        public string MOSEQ { get; set; }
        public string SHORTCODE { get; set; }
        public string CELL_NO { get; set; }
        public string MSGBODY { get; set; }
        public string MSGTYPE { get; set; }
        public string MTTOTALSEQ { get; set; }
        public string MTSEQREF { get; set; }
        public string SEND_TIME { get; set; }
        public string FINISH_TIME { get; set; }
        public string SEND_FLAG { get; set; }
        public string RESULT { get; set; }
        public DateTime? LAST_UPDATE_DATE { get; set; }
        public string CPID { get; set; }
        public string CMDCODE { get; set; }
        public string MO_MSGBODY { get; set; }
        public string RESP_TYPE { get; set; }
        public DateTime? MO_RECEIVE_TIME { get; set; }
        public DateTime? CREATE_DATE { get; set; }
    }
}
