//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGEVN.Services.Implement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MO_HIST
    {
        public string CELL_NO { get; set; }
        public string SHORTCODE { get; set; }
        public string MOSEQ { get; set; }
        public string CMDCODE { get; set; }
        public string MSGBODY { get; set; }
        public System.DateTime RECEIVE_TIME { get; set; }
        public string FILENAME { get; set; }
        public string FILEDATE { get; set; }
        public string TRANSFER_FLAG { get; set; }
        public DateTime? TRANSFER_DATE { get; set; }
    }
}
