//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGEVN.Services.Implement
{
    using System;
    using System.Collections.Generic;

    public sealed class TB_ORDER_SHIP_HIST
    {
        public string INV_ORG { get; set; }
        public string SHIPTO_CODE { get; set; }
        public string SHIPTO_NAME { get; set; }
        public string CITY { get; set; }
        public string ORDER_NO { get; set; }
        public string LINE_NO { get; set; }
        public string LINE_STATUS { get; set; }
        public string PROD_DIV { get; set; }
        public string MODEL_SUFFIX { get; set; }
        public string ORDER_QTY { get; set; }
        public string RELEASE_QTY { get; set; }
        public string UNIT_SELL_PRICE { get; set; }
        public string ORDER_AMT { get; set; }
        public string SHIPPING_METHOD { get; set; }
        public DateTime? REQUEST_SHIPPED_DATE { get; set; }
        public System.DateTime REQUEST_ARRIVAL_DATE { get; set; }
        public string SHIPPING_REMARK { get; set; }
        public string INVOICE_NO { get; set; }
        public DateTime? INVOICE_DATE { get; set; }
        public DateTime? BOOKED_DATE { get; set; }
        public string PICK_NO { get; set; }
        public DateTime? PICK_RELEASE_DATE { get; set; }
        public string DELIVERY_NO { get; set; }
        public string SUBINVENTORY { get; set; }
        public DateTime? CREATION_DATE { get; set; }
        public string BILLTO_CODE { get; set; }
        public string BILLTO_NAME { get; set; }
        public string SALESCHANNEL_CODE { get; set; }
        public string SALESCHANNEL_NAME { get; set; }
        public string CREATED_BY { get; set; }
        public string SALESPERSON { get; set; }
        public System.DateTime UNIQUE_ID { get; set; }
        public string PICK_SEQ { get; set; }
        public string MODEL { get; set; }
        public string SUFFIX { get; set; }
        public string AR_FLAG { get; set; }
        public string AU_CODE { get; set; }
        public string ACCEPTANCE_CODE { get; set; }
        public string CARRIER { get; set; }
        public string ORDER_TYPE_NAME { get; set; }
        public string CANCEL_FLAG { get; set; }
    }
}
