//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LGEVN.Services.Implement
{
    using System;
    using System.Collections.Generic;

    public sealed class TB_SN_SO_WT_MST0
    {
        public string MODEL { get; set; }
        public string SUFFIX { get; set; }
        public string SERIAL_NO { get; set; }
        public DateTime? WT_START_DATE { get; set; }
        public DateTime? WT_END_DATE { get; set; }
        public string END_USER_CELL { get; set; }
        public string WT_RESP_MSG { get; set; }
        public string WT_RESP_TYPE { get; set; }
        public string SMS_YN { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string WT_CFM_USER { get; set; }
        public DateTime? LAST_UPDATE_DATE { get; set; }
        public DateTime? SELLIN_DATE { get; set; }
        public DateTime? SELLOUT_DATE { get; set; }
        public string SELLOUT_TIME { get; set; }
        public string TRANSFER_FLAG { get; set; }
        public DateTime? TRANSFER_DATE { get; set; } 
    }
}
