//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace TestApplication.LGServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendSelloutDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSelloutDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::TestApplication.Properties.Settings.Default.TestApplication_LGServices_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendSelloutDataCompletedEventHandler SendSelloutDataCompleted;
        
        /// <remarks/>
        public event GetSelloutDataCompletedEventHandler GetSelloutDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSelloutData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendSelloutData(Sellout sellout) {
            object[] results = this.Invoke("SendSelloutData", new object[] {
                        sellout});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendSelloutDataAsync(Sellout sellout) {
            this.SendSelloutDataAsync(sellout, null);
        }
        
        /// <remarks/>
        public void SendSelloutDataAsync(Sellout sellout, object userState) {
            if ((this.SendSelloutDataOperationCompleted == null)) {
                this.SendSelloutDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSelloutDataOperationCompleted);
            }
            this.InvokeAsync("SendSelloutData", new object[] {
                        sellout}, this.SendSelloutDataOperationCompleted, userState);
        }
        
        private void OnSendSelloutDataOperationCompleted(object arg) {
            if ((this.SendSelloutDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSelloutDataCompleted(this, new SendSelloutDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSelloutData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Sellout GetSelloutData(string serial_no, string model) {
            object[] results = this.Invoke("GetSelloutData", new object[] {
                        serial_no,
                        model});
            return ((Sellout)(results[0]));
        }
        
        /// <remarks/>
        public void GetSelloutDataAsync(string serial_no, string model) {
            this.GetSelloutDataAsync(serial_no, model, null);
        }
        
        /// <remarks/>
        public void GetSelloutDataAsync(string serial_no, string model, object userState) {
            if ((this.GetSelloutDataOperationCompleted == null)) {
                this.GetSelloutDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSelloutDataOperationCompleted);
            }
            this.InvokeAsync("GetSelloutData", new object[] {
                        serial_no,
                        model}, this.GetSelloutDataOperationCompleted, userState);
        }
        
        private void OnGetSelloutDataOperationCompleted(object arg) {
            if ((this.GetSelloutDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSelloutDataCompleted(this, new GetSelloutDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Sellout {
        
        private string sERIAL_NOField;
        
        private System.Nullable<System.DateTime> sELLIN_DATEField;
        
        private System.Nullable<System.DateTime> sELLOUT_DATEField;
        
        private System.Nullable<System.DateTime> wT_START_DATEField;
        
        private System.Nullable<System.DateTime> wT_END_DATEField;
        
        private string sHOP_CODEField;
        
        private string sHOP_CELLField;
        
        private string sELLOUT_RESP_MSGField;
        
        private string pOINTField;
        
        private string aMTField;
        
        private string sELLOUT_RESP_TYPEField;
        
        private string sELLOUT_TIMEField;
        
        private string iNCENTIVE_CFM_FLAGField;
        
        private System.Nullable<System.DateTime> iNCENTIVE_CFM_DATEField;
        
        private string mODELField;
        
        private string sUFFIXField;
        
        private string cLOSE_FLAGField;
        
        private string cLOSE_PERIODField;
        
        private string sMS_YNField;
        
        private System.DateTime cREATE_DATEField;
        
        private string iNCENTIVE_CFM_USERField;
        
        private string cLOSE_USERField;
        
        private string iNCENTIVE_CFM_PERIODField;
        
        private System.Nullable<System.DateTime> lAST_UPDATE_DATEField;
        
        private string eND_USER_CELLField;
        
        private string tRANSFER_FLAGField;
        
        private System.Nullable<System.DateTime> tRANSFER_DATEField;
        
        /// <remarks/>
        public string SERIAL_NO {
            get {
                return this.sERIAL_NOField;
            }
            set {
                this.sERIAL_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SELLIN_DATE {
            get {
                return this.sELLIN_DATEField;
            }
            set {
                this.sELLIN_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SELLOUT_DATE {
            get {
                return this.sELLOUT_DATEField;
            }
            set {
                this.sELLOUT_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> WT_START_DATE {
            get {
                return this.wT_START_DATEField;
            }
            set {
                this.wT_START_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> WT_END_DATE {
            get {
                return this.wT_END_DATEField;
            }
            set {
                this.wT_END_DATEField = value;
            }
        }
        
        /// <remarks/>
        public string SHOP_CODE {
            get {
                return this.sHOP_CODEField;
            }
            set {
                this.sHOP_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string SHOP_CELL {
            get {
                return this.sHOP_CELLField;
            }
            set {
                this.sHOP_CELLField = value;
            }
        }
        
        /// <remarks/>
        public string SELLOUT_RESP_MSG {
            get {
                return this.sELLOUT_RESP_MSGField;
            }
            set {
                this.sELLOUT_RESP_MSGField = value;
            }
        }
        
        /// <remarks/>
        public string POINT {
            get {
                return this.pOINTField;
            }
            set {
                this.pOINTField = value;
            }
        }
        
        /// <remarks/>
        public string AMT {
            get {
                return this.aMTField;
            }
            set {
                this.aMTField = value;
            }
        }
        
        /// <remarks/>
        public string SELLOUT_RESP_TYPE {
            get {
                return this.sELLOUT_RESP_TYPEField;
            }
            set {
                this.sELLOUT_RESP_TYPEField = value;
            }
        }
        
        /// <remarks/>
        public string SELLOUT_TIME {
            get {
                return this.sELLOUT_TIMEField;
            }
            set {
                this.sELLOUT_TIMEField = value;
            }
        }
        
        /// <remarks/>
        public string INCENTIVE_CFM_FLAG {
            get {
                return this.iNCENTIVE_CFM_FLAGField;
            }
            set {
                this.iNCENTIVE_CFM_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> INCENTIVE_CFM_DATE {
            get {
                return this.iNCENTIVE_CFM_DATEField;
            }
            set {
                this.iNCENTIVE_CFM_DATEField = value;
            }
        }
        
        /// <remarks/>
        public string MODEL {
            get {
                return this.mODELField;
            }
            set {
                this.mODELField = value;
            }
        }
        
        /// <remarks/>
        public string SUFFIX {
            get {
                return this.sUFFIXField;
            }
            set {
                this.sUFFIXField = value;
            }
        }
        
        /// <remarks/>
        public string CLOSE_FLAG {
            get {
                return this.cLOSE_FLAGField;
            }
            set {
                this.cLOSE_FLAGField = value;
            }
        }
        
        /// <remarks/>
        public string CLOSE_PERIOD {
            get {
                return this.cLOSE_PERIODField;
            }
            set {
                this.cLOSE_PERIODField = value;
            }
        }
        
        /// <remarks/>
        public string SMS_YN {
            get {
                return this.sMS_YNField;
            }
            set {
                this.sMS_YNField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CREATE_DATE {
            get {
                return this.cREATE_DATEField;
            }
            set {
                this.cREATE_DATEField = value;
            }
        }
        
        /// <remarks/>
        public string INCENTIVE_CFM_USER {
            get {
                return this.iNCENTIVE_CFM_USERField;
            }
            set {
                this.iNCENTIVE_CFM_USERField = value;
            }
        }
        
        /// <remarks/>
        public string CLOSE_USER {
            get {
                return this.cLOSE_USERField;
            }
            set {
                this.cLOSE_USERField = value;
            }
        }
        
        /// <remarks/>
        public string INCENTIVE_CFM_PERIOD {
            get {
                return this.iNCENTIVE_CFM_PERIODField;
            }
            set {
                this.iNCENTIVE_CFM_PERIODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LAST_UPDATE_DATE {
            get {
                return this.lAST_UPDATE_DATEField;
            }
            set {
                this.lAST_UPDATE_DATEField = value;
            }
        }
        
        /// <remarks/>
        public string END_USER_CELL {
            get {
                return this.eND_USER_CELLField;
            }
            set {
                this.eND_USER_CELLField = value;
            }
        }
        
        /// <remarks/>
        public string TRANSFER_FLAG {
            get {
                return this.tRANSFER_FLAGField;
            }
            set {
                this.tRANSFER_FLAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> TRANSFER_DATE {
            get {
                return this.tRANSFER_DATEField;
            }
            set {
                this.tRANSFER_DATEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SendSelloutDataCompletedEventHandler(object sender, SendSelloutDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSelloutDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSelloutDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetSelloutDataCompletedEventHandler(object sender, GetSelloutDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSelloutDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSelloutDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sellout Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sellout)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591