//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace TestApplication.LGService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MorderChanelSoap", Namespace="http://tempuri.org/")]
    public partial class MorderChanel : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GET_WS_EDIOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MorderChanel() {
            this.Url = global::TestApplication.Properties.Settings.Default.TestApplication_LGService_MorderChanel;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GET_WS_EDICompletedEventHandler GET_WS_EDICompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GET_WS_EDI", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WS_RESP_PARS GET_WS_EDI(string ws_shop_code, string ws_shop_key, string serial_no, string model, string sell_date, string eucell, string euname, string euadd, string request_time) {
            object[] results = this.Invoke("GET_WS_EDI", new object[] {
                        ws_shop_code,
                        ws_shop_key,
                        serial_no,
                        model,
                        sell_date,
                        eucell,
                        euname,
                        euadd,
                        request_time});
            return ((WS_RESP_PARS)(results[0]));
        }
        
        /// <remarks/>
        public void GET_WS_EDIAsync(string ws_shop_code, string ws_shop_key, string serial_no, string model, string sell_date, string eucell, string euname, string euadd, string request_time) {
            this.GET_WS_EDIAsync(ws_shop_code, ws_shop_key, serial_no, model, sell_date, eucell, euname, euadd, request_time, null);
        }
        
        /// <remarks/>
        public void GET_WS_EDIAsync(string ws_shop_code, string ws_shop_key, string serial_no, string model, string sell_date, string eucell, string euname, string euadd, string request_time, object userState) {
            if ((this.GET_WS_EDIOperationCompleted == null)) {
                this.GET_WS_EDIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGET_WS_EDIOperationCompleted);
            }
            this.InvokeAsync("GET_WS_EDI", new object[] {
                        ws_shop_code,
                        ws_shop_key,
                        serial_no,
                        model,
                        sell_date,
                        eucell,
                        euname,
                        euadd,
                        request_time}, this.GET_WS_EDIOperationCompleted, userState);
        }
        
        private void OnGET_WS_EDIOperationCompleted(object arg) {
            if ((this.GET_WS_EDICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GET_WS_EDICompleted(this, new GET_WS_EDICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WS_RESP_PARS {
        
        private string rESP_RESULTField;
        
        private string rESP_TIMEField;
        
        private string rESP_MSGField;
        
        private string cUST_SEND_IDField;
        
        private string sHOP_CODEField;
        
        /// <remarks/>
        public string RESP_RESULT {
            get {
                return this.rESP_RESULTField;
            }
            set {
                this.rESP_RESULTField = value;
            }
        }
        
        /// <remarks/>
        public string RESP_TIME {
            get {
                return this.rESP_TIMEField;
            }
            set {
                this.rESP_TIMEField = value;
            }
        }
        
        /// <remarks/>
        public string RESP_MSG {
            get {
                return this.rESP_MSGField;
            }
            set {
                this.rESP_MSGField = value;
            }
        }
        
        /// <remarks/>
        public string CUST_SEND_ID {
            get {
                return this.cUST_SEND_IDField;
            }
            set {
                this.cUST_SEND_IDField = value;
            }
        }
        
        /// <remarks/>
        public string SHOP_CODE {
            get {
                return this.sHOP_CODEField;
            }
            set {
                this.sHOP_CODEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GET_WS_EDICompletedEventHandler(object sender, GET_WS_EDICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GET_WS_EDICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GET_WS_EDICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WS_RESP_PARS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WS_RESP_PARS)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591